# Generated by Django 2.2 on 2020-01-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_auto_20200113_0757'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usability', models.IntegerField(default=0)),
                ('design', models.IntegerField(default=0)),
                ('content', models.IntegerField(default=0)),
            ],
        ),
    ]
