# Generated by Django 2.2 on 2020-01-15 06:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_auto_20200115_0920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rating',
            name='content',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='design',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='rating',
            name='usability',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
